// Authoritative product code/name list — originally the New Inward form
// (src/pages/NewStockInward.tsx) ONLY, deliberately separate from
// PRODUCT_NAMES in stockMovementOptions.ts. As of 2026-09-07, New Outward
// (src/pages/NewStockOutward.tsx) also imports PRODUCTS directly, once a
// read-only Product Code field was added there too (see that file's header
// comment for why the two product lists couldn't stay separate once
// Outward needed a code lookup) — PRODUCT_NAMES/stockMovementOptions.ts is
// no longer imported by either Inward or Outward's product-name field.
// Single source of truth for both forms' Product Name combobox and the
// Product Code auto-fill lookup, plus (Outward only) the Billing Name
// auto-fill lookup.
export interface StockInwardProduct {
  code: string;
  name: string;
  billingName: string;
}

export const PRODUCTS: StockInwardProduct[] = [
  { code: 'HT00100', name: 'Alpha Pinene 95% -ve 24', billingName: 'Alpha Pinene' },
  { code: 'HT00101', name: 'Alpha Pinene 95 +ve 30-35', billingName: 'Alpha Pinene' },
  { code: 'HT00102', name: 'Alpha Pinene 95 -ve 30-35', billingName: 'Alpha Pinene' },
  { code: 'HT00103', name: 'Alpha Pinene 98 - ve 24 OR', billingName: 'Alpha Pinene' },
  { code: 'HT00104', name: 'Alpha Pinene 98 +ve 30-35 OR', billingName: 'Alpha Pinene' },
  { code: 'HT00105', name: 'Alpha Pinene 95% (CST 10 PPM)', billingName: 'Alpha Pinene' },
  { code: 'HT00106', name: 'Alpha Pinene 95% (CST 100 PPM)', billingName: 'Alpha Pinene' },
  { code: 'HT00107', name: 'Alpha Pinene 95% (CST 30 PPM)', billingName: 'Alpha Pinene' },
  { code: 'HT00108', name: 'Alpha pinene 97% -ve 37 OR', billingName: 'Alpha Pinene' },
  { code: 'HT00109', name: 'Alpha Pinene 99 +ve 24-35 OR', billingName: 'Alpha Pinene' },
  { code: 'HT00110', name: 'Alpha Pinene 99 -ve 24-35 OR', billingName: 'Alpha Pinene' },
  { code: 'HT00200', name: 'Beta Pinene 95%', billingName: 'Beta Pinene' },
  { code: 'HT00201', name: 'Beta Pinene 98%', billingName: 'Beta Pinene' },
  { code: 'HT00202', name: 'Beta Pinene 99%', billingName: 'Beta Pinene' },
  { code: 'HT00300', name: 'Camphene 96', billingName: 'Camphene' },
  { code: 'HT00400', name: 'Camphor Oil PFG SCL', billingName: 'Camphor Oil' },
  { code: 'HT00401', name: 'Camphor Oil PFG KKL', billingName: 'Camphor Oil' },
  { code: 'HT00410', name: 'Camphor Oil Comm HTPL', billingName: 'Camphor Oil' },
  { code: 'HT00411', name: 'Camphor Oil Comm OAL', billingName: 'Camphor Oil' },
  { code: 'HT00412', name: 'Camphor Oil Comm MOL', billingName: 'Camphor Oil' },
  { code: 'HT00420', name: 'Camphor Oil (otpt)', billingName: 'Camphor Oil' },
  { code: 'HT00421', name: 'Camphor Tops (otpt)', billingName: 'Camphor Tops' },
  { code: 'HT00500', name: 'Camphor Powder Blue HTPL', billingName: 'Camphor Powder' },
  { code: 'HT00501', name: 'Camphor Powder Swati Tablet', billingName: 'Camphor Powder' },
  { code: 'HT00502', name: 'Camphor Powder GF OAL Tablet', billingName: 'Camphor Powder' },
  { code: 'HT00503', name: 'Camphor Powder Privi', billingName: 'Camphor Powder' },
  { code: 'HT00510', name: 'Camphor Powder Green', billingName: 'Camphor Powder' },
  { code: 'HT00511', name: 'Camphor Powder BQ OAL', billingName: 'Camphor Powder' },
  { code: 'HT00512', name: 'Camphor Powder Privi Sticky 25kg', billingName: 'Camphor Powder' },
  { code: 'HT00513', name: 'Camphor Powder MOL', billingName: 'Camphor Powder' },
  { code: 'HT00520', name: 'Camphor Powder Red', billingName: 'Camphor Powder' },
  { code: 'HT00530', name: 'Camphor NATURAL 98%', billingName: 'Camphor Powder' },
  { code: 'HT00531', name: 'Camphor NATURAL 99%', billingName: 'Camphor Powder' },
  { code: 'HT00600', name: 'D-Limonene (Cutrale)', billingName: 'D-Limonene' },
  { code: 'HT00610', name: 'D-Limonene (DRT)', billingName: 'D-Limonene' },
  { code: 'HT00620', name: 'D-Limonene (MCI)', billingName: 'D-Limonene' },
  { code: 'HT00700', name: 'DD Turpentine (Pharma)', billingName: 'Turpentine' },
  { code: 'HT00701', name: 'Gum Turpentine (Brazil)', billingName: 'Turpentine' },
  { code: 'HT00702', name: 'Gum Turpentine (Vietnam)', billingName: 'Turpentine' },
  { code: 'HT00703', name: 'Gum Turpentine (Indo)', billingName: 'Turpentine' },
  { code: 'HT00704', name: 'Gum Turpentine (Africa)', billingName: 'Turpentine' },
  { code: 'HT00705', name: 'Gum Turpentine (Portugal)', billingName: 'Turpentine' },
  { code: 'HT00706', name: 'Gum Turpentine (Vetnam/ Brazil)', billingName: 'Turpentine' },
  { code: 'HT00800', name: 'Delta Carene 92%', billingName: 'Delta Carene' },
  { code: 'HT00801', name: 'Delta Carene 95%', billingName: 'Delta Carene' },
  { code: 'HT00900', name: 'Dipentene', billingName: 'Dipentene' },
  { code: 'HT00902', name: 'Dipentene (DDINDIAN)', billingName: 'Dipentene' },
  { code: 'HT00903', name: 'Dipentene (DDHTPLCST)', billingName: 'Dipentene' },
  { code: 'HT00904', name: 'DIpentene HC (DDIMP)', billingName: 'Dipentene' },
  { code: 'HT00906', name: 'Dipentene (DDBrazil)', billingName: 'Dipentene' },
  { code: 'HT00910', name: 'Dipentene CT-MOL', billingName: 'Dipentene' },
  { code: 'HT00911', name: 'Dipentene CT-PSCL', billingName: 'Dipentene' },
  { code: 'HT00912', name: 'Dipentene CT-OAL', billingName: 'Dipentene' },
  { code: 'HT00914', name: 'Dipentene CT-HTPL', billingName: 'Dipentene' },
  { code: 'HT00915', name: 'Dipentene CT-MOL-OAL', billingName: 'Dipentene' },
  { code: 'HT00916', name: 'Dipentene Brady 200', billingName: 'Dipentene' },
  { code: 'HT00917', name: 'Dipentene ZEST', billingName: 'Dipentene' },
  { code: 'HT00918', name: 'Dipentene Brady 201', billingName: 'Dipentene' },
  { code: 'HT00920', name: 'Dipentene GTOVie-RM', billingName: 'Dipentene' },
  { code: 'HT00921', name: 'Dipentene GTOIndo-RM', billingName: 'Dipentene' },
  { code: 'HT00922', name: 'Dipentene GTOBra-RM', billingName: 'Dipentene' },
  { code: 'HT00923', name: 'Dipentene GTOIndoVie-RM', billingName: 'Dipentene' },
  { code: 'HT00930', name: 'Dipentene TP', billingName: 'Dipentene' },
  { code: 'HT00940', name: 'Dipentene Asian', billingName: 'Dipentene' },
  { code: 'HT00950', name: 'Dipentene TerpCP-RM', billingName: 'Dipentene' },
  { code: 'HT01000', name: 'Fenchone 98%', billingName: 'Fenchone' },
  { code: 'HT01100', name: 'Gamma Terpinene 90%', billingName: 'Gamma Terpinene' },
  { code: 'HT01101', name: 'Gamma Terpinene 95%', billingName: 'Gamma Terpinene' },
  { code: 'HT01102', name: 'Gamma Terpinene 96%', billingName: 'Gamma Terpinene' },
  { code: 'HT01103', name: 'Gamma Terpinene 98%', billingName: 'Gamma Terpinene' },
  { code: 'HT01200', name: 'Gum Rosin B JBR', billingName: 'Rosin' },
  { code: 'HT01201', name: 'Gum Rosin B VIetnam', billingName: 'Rosin' },
  { code: 'HT01202', name: 'Gum Rosin B Indo', billingName: 'Rosin' },
  { code: 'HT01210', name: 'Gum Rosin WG Swastik', billingName: 'Rosin' },
  { code: 'HT01211', name: 'Gum Rosin WG Ganga', billingName: 'Rosin' },
  { code: 'HT01212', name: 'Gum Rosin WG Mount', billingName: 'Rosin' },
  { code: 'HT01213', name: 'Gum Rosin WG JBR', billingName: 'Rosin' },
  { code: 'HT01214', name: 'Gum Rosin WG GANPATI', billingName: 'Rosin' },
  { code: 'HT01215', name: 'Gum Rosin WG HIMAL', billingName: 'Rosin' },
  { code: 'HT01220', name: 'Gum Rosin  N', billingName: 'Rosin' },
  { code: 'HT01230', name: 'Gum Rosin  K', billingName: 'Rosin' },
  { code: 'HT01240', name: 'Gum Rosin Indo PHT', billingName: 'Rosin' },
  { code: 'HT01250', name: 'Gum Rosin Indo NON PHT', billingName: 'Rosin' },
  { code: 'HT01260', name: 'Gum Rosin WW Indian Swatik', billingName: 'Rosin' },
  { code: 'HT01270', name: 'Gum Rosin WW Mount', billingName: 'Rosin' },
  { code: 'HT01280', name: 'Gum Rosin Latin America', billingName: 'Rosin' },
  { code: 'HT01290', name: 'Gum Rosin Brazil', billingName: 'Rosin' },
  { code: 'HT01300', name: 'Gum Rosin X Mount', billingName: 'Gum Rosin' },
  { code: 'HT01310', name: 'Tall Oil Rosin', billingName: 'Rosin' },
  { code: 'HT01320', name: 'Gum Rosin M', billingName: 'Gum Rosin' },
  { code: 'HT01400', name: 'Isoborneol (HTPL)', billingName: 'Isoborneol' },
  { code: 'HT01410', name: 'Isoborneol (GP)', billingName: 'Isoborneol' },
  { code: 'HT01420', name: 'Isoborneol (PSCL)', billingName: 'Isoborneol' },
  { code: 'HT01430', name: 'Isoborneol (MOL)', billingName: 'Isoborneol' },
  { code: 'HT01440', name: 'Isoborneol (OAL)', billingName: 'Isoborneol' },
  { code: 'HT01450', name: 'Isoborneol (KKL)', billingName: 'Isoborneol' },
  { code: 'HT01460', name: 'Isoborneol (HELLO)', billingName: 'Isoborneol' },
  { code: 'HT01500', name: 'Isobornyl Acetate PFG 94%', billingName: 'Isobornyl Acetate' },
  { code: 'HT01600', name: 'Isoborneol Flakes [VDH]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01610', name: 'Isoborneol Flakes Big [MOL]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01611', name: 'Isoborneol Flakes small [MOL]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01620', name: 'Isoborneol Flakes [DIV]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01630', name: 'Isoborneol Flakes [RAMPER]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01640', name: 'Isoborneol Flakes [YAARA]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01650', name: 'Isoborneol Flakes [NATURAL BIO.]', billingName: 'Isoborneol Flakes' },
  { code: 'HT01700', name: 'Longifolene 80 Indian', billingName: 'Longifolene' },
  { code: 'HT01701', name: 'Longifolene 80 China', billingName: 'Longifolene' },
  { code: 'HT01702', name: 'Longifolene 80 Europe', billingName: 'Longifolene' },
  { code: 'HT01710', name: 'Longifolene 90 Indian', billingName: 'Longifolene' },
  { code: 'HT01711', name: 'Longifolene 90 China', billingName: 'Longifolene' },
  { code: 'HT01750', name: 'Longi Super', billingName: 'Longifolene' },
  { code: 'HT01800', name: 'Pine Oil 211', billingName: 'Pine Oil 211' },
  { code: 'HT01801', name: 'Pine Oil 211 (DD)', billingName: 'Pine Oil 211' },
  { code: 'HT01802', name: 'Pine Oil 211 (DTIMP)', billingName: 'Pine Oil 211' },
  { code: 'HT01803', name: 'Pine Oil 211 (Limo)', billingName: 'Pine Oil 211' },
  { code: 'HT01804', name: 'Pine Oil 211 (DIPC)', billingName: 'Pine Oil 211' },
  { code: 'HT01805', name: 'Pine Oil 211 (DDTO)', billingName: 'Pine Oil 211' },
  { code: 'HT01810', name: 'Pine Oil 311 (22%)', billingName: 'Pine Oil 311' },
  { code: 'HT01811', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01812', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01813', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01814', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01815', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01816', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01817', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01818', name: 'Pine Oil 311 (tobe finialised)', billingName: 'Pine Oil 311' },
  { code: 'HT01820', name: 'Pine Oil 411 (32%)', billingName: 'Pine Oil 411' },
  { code: 'HT01821', name: 'Pine Oil 411 (tobe finialised)', billingName: 'Pine Oil' },
  { code: 'HT01822', name: 'Pine Oil 411 (tobe finialised)', billingName: 'Pine Oil' },
  { code: 'HT01823', name: 'Pine Oil 411 (tobe finialised)', billingName: 'Pine Oil' },
  { code: 'HT01824', name: 'Pine Oil 411 (tobe finialised)', billingName: 'Pine Oil' },
  { code: 'HT01829', name: 'Pine Oil 40 (ROB)', billingName: 'Pine Oil 40' },
  { code: 'HT01830', name: 'Pine Oil 50 (PFG)', billingName: 'Pine Oil 50' },
  { code: 'HT01831', name: 'Pine Oil 50 (HPTerpi)', billingName: 'Pine Oil 50' },
  { code: 'HT01832', name: 'Pine Oil 50 (HPTM)', billingName: 'Pine Oil 50' },
  { code: 'HT01840', name: 'Pine Oil 511 (40% To 42%)', billingName: 'Pine Oil 511' },
  { code: 'HT01841', name: 'Pine Oil 511+ (DipTTA25%)', billingName: 'Pine Oil 511' },
  { code: 'HT01842', name: 'Pine Oil 511 (tobe finialised)', billingName: 'Pine Oil 511' },
  { code: 'HT01850', name: 'Pine Oil 65', billingName: 'Pine Oil 65' },
  { code: 'HT01851', name: 'Pine Oil 65 (HPTerpi)', billingName: 'Pine Oil 65' },
  { code: 'HT01852', name: 'Pine Oil 65 (HPTM)', billingName: 'Pine Oil 65' },
  { code: 'HT01860', name: 'Pine Oil 70', billingName: 'Pine Oil 70' },
  { code: 'HT01861', name: 'Pine Oil 70 (HPTerpi)', billingName: 'Pine Oil 70' },
  { code: 'HT01862', name: 'Pine Oil 70 (HPTM)', billingName: 'Pine Oil 70' },
  { code: 'HT01870', name: 'PINE OIL 85(GPI)', billingName: 'PINE OIL 85' },
  { code: 'HT01871', name: 'PINE OIL 85 (PG)', billingName: 'PINE OIL 85' },
  { code: 'HT01872', name: 'PINE OIL 85 (HP Terpi)', billingName: 'PINE OIL 85' },
  { code: 'HT01873', name: 'PINE OIL 85 (HP TM)', billingName: 'PINE OIL 85' },
  { code: 'HT01874', name: 'PINE OIL 85 (OTHPTerpi)', billingName: 'PINE OIL 85' },
  { code: 'HT01875', name: 'PINE OIL 85 (OTHPTM)', billingName: 'PINE OIL 85' },
  { code: 'HT01876', name: 'PINE OIL 85 (CST)', billingName: 'PINE OIL 85' },
  { code: 'HT01877', name: 'PINE OIL Super 85', billingName: 'PINE OIL 85' },
  { code: 'HT01899', name: 'Pine Oil Special', billingName: 'Pine Oil' },
  { code: 'HT01900', name: 'PINE OIL 90 (HP Terpi)', billingName: 'PINE OIL 90' },
  { code: 'HT01910', name: 'Pine Tar 100 (GTO)', billingName: 'Pine Tar' },
  { code: 'HT01920', name: 'Pine Tar 200 (TerpGPI)', billingName: 'Pine Tar' },
  { code: 'HT01930', name: 'Pine Tar 300 (DIP)', billingName: 'Pine Tar' },
  { code: 'HT01940', name: 'Pine Tar 400 (THP)', billingName: 'Pine Tar' },
  { code: 'HT01950', name: 'Pine Tar 500 (IBA)', billingName: 'Pine Tar' },
  { code: 'HT01960', name: 'Pine Tar 600 (Camphor)', billingName: 'Pine Tar' },
  { code: 'HT01970', name: 'Pine Tar 700 (Gamma)', billingName: 'Pine Tar' },
  { code: 'HT02000', name: 'SODIUM ACETATE TRIHYDRATE', billingName: 'SODIUM ACETATE TRIHYDRATE' },
  { code: 'HT02100', name: 'Terpene 100', billingName: 'Terpene' },
  { code: 'HT02101', name: 'Mixed Terpenes', billingName: 'Terpene' },
  { code: 'HT02102', name: 'Terpene 610', billingName: 'Terpene' },
  { code: 'HT02103', name: 'Terpene 620', billingName: 'Terpene' },
  { code: 'HT02104', name: 'Terpene 650', billingName: 'Terpene' },
  { code: 'HT02105', name: 'Terpene 5098', billingName: 'Terpene' },
  { code: 'HT02200', name: 'Terpineol Comm GPI', billingName: 'Terpineol' },
  { code: 'HT02270', name: 'Terpineol DG', billingName: 'Terpineol' },
  { code: 'HT02250', name: 'Terpineol EP / Alpha Terpineol 92 % GPI', billingName: 'Terpineol' },
  { code: 'HT02251', name: 'Terpineol EP Super / Alpha Terpineol Super', billingName: 'Terpineol' },
  { code: 'HT02260', name: 'Terpineol CP GPI', billingName: 'Terpineol' },
  { code: 'HT02261', name: 'Terpineol CP Import', billingName: 'Terpineol' },
  { code: 'HT02280', name: 'Terpineol MG', billingName: 'Terpineol' },
  { code: 'HT02290', name: 'Terpineol MU', billingName: 'Terpineol' },
  { code: 'HT02210', name: 'Terpineol HP', billingName: 'Terpineol' },
  { code: 'HT02220', name: 'Terpineol 70 (HPTerpi)', billingName: 'Terpineol' },
  { code: 'HT02221', name: 'Terpineol 70 (CommTerpi)', billingName: 'Terpineol' },
  { code: 'HT02222', name: 'Terpineol 70(HP TM)', billingName: 'Terpineol' },
  { code: 'HT02223', name: 'Terpineol 70(OTHPTerpi)', billingName: 'Terpineol' },
  { code: 'HT02224', name: 'Terpineol 70(OTHPTM)', billingName: 'Terpineol' },
  { code: 'HT02225', name: 'Terpineol 70(CST)', billingName: 'Terpineol' },
  { code: 'HT02230', name: 'Terpineol 85 (HP Terpi)', billingName: 'Terpineol' },
  { code: 'HT02231', name: 'Terpineol 85 (HP TM)', billingName: 'Terpineol' },
  { code: 'HT02232', name: 'Terpineol 85 (OTHPTerpi)', billingName: 'Terpineol' },
  { code: 'HT02233', name: 'Terpineol 85 (OTHPTM)', billingName: 'Terpineol' },
  { code: 'HT02234', name: 'Terpineol 85 (CST)', billingName: 'Terpineol' },
  { code: 'HT02240', name: 'Terpineol PG 85% GPI', billingName: 'Terpineol' },
  { code: 'HT02300', name: 'Terpinyl Acetate +ve 12', billingName: 'Terpinyl Acetate' },
  { code: 'HT02301', name: 'Terpinyl Acetate +ve 14', billingName: 'Terpinyl Acetate' },
  { code: 'HT02302', name: 'Terpinyl Acetate +ve 18-20', billingName: 'Terpinyl Acetate' },
  { code: 'HT02303', name: 'Terpinyl Acetate PFG', billingName: 'Terpinyl Acetate' },
  { code: 'HT02304', name: 'Terpinyl Acetate PFG Super', billingName: 'Terpinyl Acetate' },
  { code: 'HT02305', name: 'Terpinyl Acetate Tops', billingName: 'Terpinyl Acetate' },
  { code: 'HT02400', name: 'Terpinolene 20', billingName: 'Terpinolene' },
  { code: 'HT02401', name: 'Terpinolene 20 Geeta', billingName: 'Terpinolene' },
  { code: 'HT02410', name: 'Terpinolene 30', billingName: 'Terpinolene' },
  { code: 'HT02411', name: 'Terpinolene 30 (SHK)', billingName: 'Terpinolene' },
  { code: 'HT02420', name: 'Terpinolene 90 (PFG)', billingName: 'Terpinolene' },
  { code: 'HT02421', name: 'Terpinolene 90 (CAM)', billingName: 'Terpinolene' },
  { code: 'HT02422', name: 'Terpinolene 90 (Dual)', billingName: 'Terpinolene' },
  { code: 'HT02423', name: 'Terpinolene 90 (BHT)', billingName: 'Terpinolene' },
  { code: 'HT02430', name: 'Terpinolene SPL', billingName: 'Terpinolene' },
  { code: 'HT02500', name: 'Anthamber Residue / Dhoop Residue Brown Black', billingName: 'Anthamber Residue' },
  { code: 'HT02501', name: 'PCM Residue PSCL', billingName: 'Anthamber Residue' },
  { code: 'HT02502', name: 'AF Residue Dark Yellow (0.89-0.93)', billingName: 'Anthamber Residue' },
  { code: 'HT02503', name: 'AF + Geraniol Residue', billingName: 'Anthamber Residue' },
  { code: 'HT02600', name: 'Anthamber Tops (W)', billingName: 'Anthamber Tops' },
  { code: 'HT02601', name: 'Anthamber Tops (Y) 100', billingName: 'Anthamber Tops' },
  { code: 'HT02602', name: 'Anthamber Tops (Y) 200 (2601+2103)', billingName: 'Anthamber Tops' },
  { code: 'HT02700', name: 'Carvacrol', billingName: 'Carvacrol' },
  { code: 'HT02800', name: 'CITRONELLA TOPS', billingName: 'CITRONELLA TOPS' },
  { code: 'HT02900', name: 'Derlic', billingName: 'Delta-3-Carene' },
  { code: 'HT03000', name: 'DHM Residue (P)', billingName: 'DHM Residue' },
  { code: 'HT03001', name: 'DHM Residue (A)', billingName: 'DHM Residue' },
  { code: 'HT03100', name: 'DHM Tops (W)', billingName: 'DHM Tops' },
  { code: 'HT03101', name: 'DHM Tops (Y) 100', billingName: 'DHM Tops' },
  { code: 'HT03102', name: 'DHM Tops (Y) 200', billingName: 'DHM Tops' },
  { code: 'HT03200', name: 'DL-Limonene 65%', billingName: 'DL-Limonene' },
  { code: 'HT03201', name: 'DL-Limonene 80%', billingName: 'DL-Limonene' },
  { code: 'HT03202', name: 'DL-Limonene 85%', billingName: 'DL-Limonene' },
  { code: 'HT03203', name: 'DL-Limonene 90%', billingName: 'DL-Limonene' },
  { code: 'HT03300', name: 'Ester Gum (FOOD) Lumps Magni', billingName: 'Ester Gum' },
  { code: 'HT03301', name: 'Ester Gum (FOOD)  Pellets Magni', billingName: 'Ester Gum' },
  { code: 'HT03302', name: 'Ester Gum (FOOD) Pellets CCPL', billingName: 'Ester Gum' },
  { code: 'HT03303', name: 'Ester Gum (FOOD) Pellets Shree', billingName: 'Ester Gum' },
  { code: 'HT03304', name: 'Ester Gum (FOOD) Pellets SPAC', billingName: 'Ester Gum' },
  { code: 'HT03310', name: 'Ester Gum Adhesives Magni Lumps', billingName: 'Ester Gum' },
  { code: 'HT03311', name: 'Ester Gum Adhesives CCPL Pellets', billingName: 'Ester Gum' },
  { code: 'HT03400', name: 'Geraniol HB/ Geraniol Citronella Residue', billingName: 'Geraniol HB' },
  { code: 'HT03500', name: 'Geraniol Tops', billingName: 'Geraniol Tops' },
  { code: 'HT03600', name: 'Isolongifolene Keton Comm', billingName: 'Isolongifolene Keton Comm' },
  { code: 'HT03601', name: 'Isolongifolene Keton', billingName: 'Isolongifolene Keton Comm' },
  { code: 'HT03700', name: 'L-Limonene', billingName: 'L-Limonene' },
  { code: 'HT03800', name: 'LEMON TERPENES', billingName: 'LEMON TERPENES' },
  { code: 'HT03900', name: 'Lemongrass Oil', billingName: 'Lemongrass Oil' },
  { code: 'HT04000', name: 'LINALOOL NAT', billingName: 'LINALOOL NAT' },
  { code: 'HT04100', name: 'Methyl Pentanone HB (MPO HB)', billingName: 'Methyl Pentanone' },
  { code: 'HT04101', name: 'Methyl Pentenone HF', billingName: 'Methyl Pentanone' },
  { code: 'HT04200', name: 'Orange Oil', billingName: 'Orange Oil' },
  { code: 'HT04300', name: 'OT PT', billingName: 'OT PT' },
  { code: 'HT04400', name: 'Terpin Hydrate Powder', billingName: 'Terpin Hydrate Powder' },
  { code: 'HT04500', name: 'Terpinen-4-OL 96%', billingName: 'Terpinen-4-OL' },
  { code: 'HT04501', name: 'Terpinen-4-OL 98%', billingName: 'Terpinen-4-OL' },
  { code: 'HT04502', name: 'Terpinen-4-OL Comm (80-90%)', billingName: 'Terpinen-4-OL' },
  { code: 'HT04503', name: 'Terpinen-4-OL 97%', billingName: 'Terpinen-4-OL' },
  { code: 'HT04700', name: 'Timber Touch Tops', billingName: 'Timber Touch Tops' },
  { code: 'HT04800', name: 'Titanium Recycle', billingName: 'Titanium Recycle' },
  { code: 'HT04900', name: 'TMCM T & B Residue', billingName: 'TMCM T & B Residue' },
];
