import React, { useState, useMemo, useEffect, useRef, useCallback } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Search, List, Columns3, CheckCircle2 } from 'lucide-react';
import { useAppStore } from '../store';
import { Badge, Button } from '../components/ui';
import { customerOfDoc, canDeleteRecords, formatINR, fmtIST, doerLabel, siteLabel, resolveAdjustments, maxItemGstRate, normalizeSearchText, totalRemaining, canActOnDispatchBoard } from '../lib/utils';
import { Order, OrderItem, DispatchEntry, DispatchFulfillmentType } from '../lib/types';
import { buildBoard, mapStepFromDB, stepDef, lastStepClick, describeStepClick,BoardCard, BoardOrderCard, DispatchStepRecord, StepAction, StepNo, DONE_COLUMN } from '../lib/dispatchFlow';
import { DispatchBoard, AutoTag, StepActionButtons } from '../components/DispatchBoard';
import { DispatchDrawer, StepEditPatch } from '../components/DispatchDrawer';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { friendlyDeleteError } from '../lib/cascadeDelete';
import { supabase } from '../lib/supabase';
import { logActivity } from '../lib/activityLog';

type SubType = DispatchFulfillmentType | 'not_set';
type DispatchTab = 'pending' | 'dispatched' | 'emailSent';

const thBase = 'font-mono text-[8.5px] font-bold tracking-[1.5px] uppercase text-g500 px-[13px] py-[9px] whitespace-nowrap border-b border-g200';
const thCls = `${thBase} text-left`;
const thRightCls = `${thBase} text-right`;
const pillCls = (active: boolean) => `px-[11px] py-1 rounded-[3px] text-[11.5px] font-medium cursor-pointer transition-colors whitespace-nowrap select-none ${active ? 'bg-white text-blk font-semibold shadow-[0_1px_3px_rgba(0,0,0,0.08)]' : 'text-g600 hover:text-blk'}`;

// Same "Punched At" recency colouring as Orders.tsx: today = green, within 7 days = amber, older = neutral.
function punchedAtClass(createdAt: string): { text: string; title?: string } {
  const now = new Date(); now.setHours(0, 0, 0, 0);
  const punched = new Date(createdAt); punched.setHours(0, 0, 0, 0);
  const days = Math.round((now.getTime() - punched.getTime()) / 86400000);
  if (days === 0) return { text: 'text-emerald-600 font-semibold', title: 'Punched today' };
  if (days <= 7) return { text: 'text-amber-600 font-semibold', title: `${days} day(s) ago` };
  return { text: 'text-g600' };
}

const fulfillmentLabel = (t: SubType) => t === 'self_pickup' ? 'Self Pickup' : t === 'delivery' ? 'Delivery' : 'Not Set';

// Dispatch entries bulk-imported from old "Delivered" orders (before the
// Dispatch module existed) carry created_by = 'system-import'. They're
// skipped by automatic SO numbering and show "—" in SO No. Editing one in
// the form never changes created_by (the form doesn't send it), so this
// sticks.
const IMPORTED_CREATED_BY = 'system-import';
const isImportedEntry = (e: DispatchEntry) => e.createdBy === IMPORTED_CREATED_BY;

// `hasOrder` false = dispatch entry with no linked order (or an imported
// entry, which never gets an SO number) → "—"; otherwise a
// missing number is still being generated by ensureSoNumbers → "…".
function SoCell({ soNumber, hasOrder }: { soNumber?: string; hasOrder: boolean }) {
  if (soNumber) return <span className="font-mono text-[10.5px] font-bold text-sW">{soNumber}</span>;
  return hasOrder ? <span className="font-mono text-[10.5px] text-g400" title="Generating SO number…">…</span> : <span className="text-g400">—</span>;
}

// Expanded line-item table, shared by all three tabs.
function LineItemsPanel({ title, items, grand }: { title: string; items: OrderItem[]; grand: number }) {
  const subTotal = items.reduce((s, i) => s + i.total, 0);
  const itemGst = items.reduce((s, i) => s + (i.total * i.gst / 100), 0);
  return (
    <div className="p-[10px_16px]">
      <div className="font-mono text-[8px] font-bold tracking-[2px] uppercase text-sW mb-[7px]">{title}</div>
      {items.length === 0 ? (
        <div className="text-g400 text-[11.5px] py-2">No line items recorded.</div>
      ) : (
        <table className="w-full border-collapse text-[11.5px] m-0 mb-2">
          <thead className="bg-g100">
            <tr>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-left border-b border-g200">#</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-left border-b border-g200">Product Name</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-left border-b border-g200">HSN Code</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-right border-b border-g200">No of Barrels</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-right border-b border-g200">Packing</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-right border-b border-g200">Total Qty</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-left border-b border-g200">Packing Type</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-right border-b border-g200">Unit Rate (₹)</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-right border-b border-g200">GST%</th>
              <th className="font-mono text-[8px] tracking-[1px] uppercase text-g400 px-2.5 py-1.5 text-right border-b border-g200">Amount (₹)</th>
            </tr>
          </thead>
          <tbody>
            {items.map(i => {
              const packNum = parseFloat(i.packing || '');
              const totalQty = i.qty > 0 && packNum > 0 ? i.qty * packNum : null;
              return (
                <tr key={i.seq}>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-[10px] text-g400 w-6">{i.seq}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-medium">{i.desc}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-[10px]">{i.hsn || '—'}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-[11.5px] font-bold text-right">{i.qty}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-[11px] text-right">{i.packing || '—'}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-[11.5px] font-bold text-right">{totalQty ?? '—'}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk text-[11px] text-g600">{i.packingType || '—'}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-right">{formatINR(i.agreedRate)}</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono text-right">{i.gst}%</td>
                  <td className="px-2.5 py-1.5 border-b border-g100 text-blk font-mono font-bold text-right">{formatINR(i.total)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      )}
      {items.length > 0 && (
        <div className="flex justify-end pt-2 border-t border-g200 gap-5 items-center">
          <span className="text-[12px] text-g600">Sub-Total: <strong className="text-blk font-bold font-mono">{formatINR(subTotal)}</strong></span>
          <span className="text-[12px] text-g600">GST: <strong className="text-blk font-bold font-mono">{formatINR(Math.round(itemGst))}</strong></span>
          <span className="text-[13px] text-red-mrt font-bold font-mono tracking-tight">Grand: {formatINR(Math.round(grand))}</span>
        </div>
      )}
    </div>
  );
}

export function Dispatch() {
  const navigate = useNavigate();
  const { data, user, deleteDispatchEntry, ensureSoNumbers, isReadOnlyUser, isAdmin, removeOrderFromDispatch } = useAppStore();
  const canDelete = canDeleteRecords(user?.email);

  // Initial tab/pill come from the URL (?tab=pending|dispatched|emailSent
  // &type=delivery|self_pickup) — NewDispatchEntry.tsx sends the user back
  // here that way after Save / Email to Client so they land on the entry
  // they just made. Anything else (incl. the retired ?tab=toDispatch)
  // falls back to Pending.
  const [searchParams, setSearchParams] = useSearchParams();
  const [tab, setTab] = useState<DispatchTab>(() => {
    const t = searchParams.get('tab');
    return t === 'dispatched' || t === 'emailSent' ? t : 'pending';
  });
  const [subType, setSubType] = useState<DispatchFulfillmentType>(() =>
    searchParams.get('type') === 'self_pickup' ? 'self_pickup' : 'delivery');
  const [expandedRow, setExpandedRow] = useState<string | null>(null);
  const [search, setSearch] = useState('');

  // Table (this page as it always was) vs the Kanban Board view — kept in
  // the URL as ?view=board so a refresh stays on the board.
  const [view, setView] = useState<'table' | 'board'>(() => searchParams.get('view') === 'board' ? 'board' : 'table');
  const [boardFilter, setBoardFilter] = useState<'all' | 'delayed' | 'hold'>('all');
  const [boardType, setBoardType] = useState<'both' | DispatchFulfillmentType>('both');
  // Board timers ("Due in 12 min", "Late by 1h 20m") re-evaluate every minute.
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (view !== 'board') return;
    setNow(Date.now());
    const t = setInterval(() => setNow(Date.now()), 60000);
    return () => clearInterval(t);
  }, [view]);

  // Board step history (dispatch_steps — steps 1–7 only; 8–10 come from the
  // dispatch entries themselves). Loaded when the board opens and refreshed
  // on the same 1-minute tick, so clicks made by someone else show up
  // without a page reload.
  const [stepRecords, setStepRecords] = useState<DispatchStepRecord[]>([]);
  useEffect(() => {
    if (view !== 'board') return;
    supabase.from('dispatch_steps').select('*').then(({ data: rows, error }) => {
      if (error) { console.error('Error loading dispatch steps:', error); return; }
      setStepRecords((rows || []).map(mapStepFromDB));
    });
  }, [view, now]);

  // Done / Hold / Resume on steps 1–7: Samata (mum@) + ADMIN_EMAILS only;
  // everyone else sees the board read-only. Never changes an order's status.
  const canActOnBoard = canActOnDispatchBoard(user?.email) && !isReadOnlyUser;
  const [busyCardKey, setBusyCardKey] = useState<string | null>(null);
  const stepLogLabel = (o: Order, stepNo: number, what: string) =>
    `${o.soNumber || o.id} · Step ${stepNo} ${stepDef(stepNo as StepNo).title} · ${what}`;

  const runStepAction = async (card: BoardOrderCard, action: StepAction, remark?: string) => {
    if (!canActOnBoard || busyCardKey) return;
    setBusyCardKey(card.key);
    try {
      const nowIso = new Date().toISOString();
      const rows = action.writes.map((w, i) => ({
        order_id: card.order.id,
        round: card.position.round,
        step_no: w.stepNo,
        status: w.status,
        planned_at: w.stepNo === card.position.step ? card.position.plannedAt ?? null : null,
        // A hold's done_at is filled in later, when it's resumed.
        done_at: w.status === 'hold' ? null : nowIso,
        done_by: user?.email ?? null,
        remark: i === 0 && remark?.trim() ? remark.trim() : null,
      }));
      const { data: inserted, error } = await supabase.from('dispatch_steps').insert(rows).select('*');
      if (error) throw error;
      setStepRecords(prev => [...prev, ...(inserted || []).map(mapStepFromDB)]);
      for (const row of inserted || []) {
        const what = row.status === 'done' ? `Done (${action.label})` : row.status === 'skipped' ? 'Skipped' : 'On hold';
        logActivity({ module: 'dispatch_steps', recordId: card.order.id, recordLabel: stepLogLabel(card.order, row.step_no, what), action: 'insert', after: row });
      }
    } catch (err: any) {
      alert(`Could not save: ${err?.message || JSON.stringify(err)}`);
    } finally {
      setBusyCardKey(null);
    }
  };

  const resumeHold = async (card: BoardOrderCard, remark?: string) => {
    const hold = card.position.hold?.record;
    if (!canActOnBoard || busyCardKey || !hold) return;
    setBusyCardKey(card.key);
    try {
      const resumedAt = new Date().toISOString();
      const patch: Record<string, any> = { done_at: resumedAt, done_by: user?.email ?? null };
      if (remark?.trim()) patch.remark = [hold.remark, remark.trim()].filter(Boolean).join(' · ');
      const { error } = await supabase.from('dispatch_steps').update(patch).eq('id', hold.id);
      if (error) throw error;
      setStepRecords(prev => prev.map(r => r.id === hold.id ? { ...r, doneAt: resumedAt, doneBy: patch.done_by ?? undefined, remark: patch.remark ?? r.remark } : r));
      logActivity({
        module: 'dispatch_steps', recordId: card.order.id, recordLabel: stepLogLabel(card.order, hold.stepNo, 'Resumed'),
        action: 'update', before: { status: 'hold', resumed_at: null }, after: { status: 'resumed', resumed_at: resumedAt },
      });
    } catch (err: any) {
      alert(`Could not resume: ${err?.message || JSON.stringify(err)}`);
    } finally {
      setBusyCardKey(null);
    }
  };

  // 2026-10-05: Step 6 "DO issued ✓" no longer marks the step done straight
  // away — the Stock Movements Outward form has to be saved first.
  // 2026-10-06: that form now opens as a normal FULL PAGE (like New Enquiry)
  // instead of a popup over the board. We only navigate here; the page
  // (NewStockOutward.tsx, ?fromDispatch=1) prefills itself from the order,
  // and after its save it writes the Step 6 dispatch_steps row and comes
  // back to the board. Back/Cancel there = nothing changes.
  const handleStepAction = (card: BoardOrderCard, action: StepAction, remark?: string) => {
    if (card.position.step === 6 && action.primary) {
      if (!canActOnBoard || busyCardKey) return;
      const params = new URLSearchParams({
        fromDispatch: '1',
        orderRef: card.order.id,
        round: String(card.position.round),
        plannedAt: card.position.plannedAt || '',
      });
      // Remark typed in the drawer travels along, so it is still saved on the step.
      if (remark?.trim()) params.set('remark', remark.trim());
      navigate(`/stock-movements/new-outward?${params.toString()}`);
      return;
    }
    return runStepAction(card, action, remark);
  };

  // 2026-10-06: step buttons are shown to every login; canAct decides whether
  // they can be clicked (disabled + tooltip otherwise). The guards inside
  // runStepAction / resumeHold / handleStepAction stay as the real lock.
  const renderBoardActions = (card: BoardCard) => card.kind === 'order'
    ? <StepActionButtons card={card} busy={busyCardKey === card.key} canAct={canActOnBoard} onAction={handleStepAction} onResume={resumeHold} />
    : null;

  // Admin-only "Undo last step" (drawer): takes back the order's most recent
  // step 1–7 click — deletes that click's dispatch_steps rows, or un-resumes
  // a resumed hold. Only dispatch_steps is touched; never dispatch entries,
  // the order, or its status.
  const canUndoOnBoard = isAdmin && !isReadOnlyUser;
  const [undoBusy, setUndoBusy] = useState(false);
  const undoLastStep = async (order: Order) => {
    if (!canUndoOnBoard || undoBusy) return;
    const click = lastStepClick(stepRecords.filter(r => r.orderId === order.id));
    if (!click) return;
    const what = describeStepClick(click);
    const by = click.kind === 'delete' ? click.rows[0].doneBy : click.row.doneBy;
    const when = fmtIST(new Date(click.at), 'dd MMM, hh:mm a');
    if (!confirm(`Undo the last step for ${order.soNumber || order.id}?\n\n${what}\n(${when}${by ? ` by ${doerLabel(by, data.roster)}` : ''})\n\nThe card moves back to where it was. Dispatch entries and the order's status are not changed.`)) return;
    setUndoBusy(true);
    try {
      const label = `${order.soNumber || order.id} · Undo · ${what}`;
      if (click.kind === 'delete') {
        const ids = click.rows.map(r => r.id);
        const { data: deleted, error } = await supabase.from('dispatch_steps').delete().in('id', ids).select('id');
        if (error) throw error;
        if ((deleted || []).length !== ids.length) throw new Error('The step could not be removed (it may already have been undone). Refresh and try again.');
        setStepRecords(prev => prev.filter(r => !ids.includes(r.id)));
        logActivity({ module: 'dispatch_steps', recordId: order.id, recordLabel: label, action: 'delete', before: { undone: click.rows } });
      } else {
        const { data: updated, error } = await supabase.from('dispatch_steps').update({ done_at: null }).eq('id', click.row.id).select('id');
        if (error) throw error;
        if ((updated || []).length !== 1) throw new Error('The resume could not be undone. Refresh and try again.');
        setStepRecords(prev => prev.map(r => r.id === click.row.id ? { ...r, doneAt: undefined } : r));
        logActivity({
          module: 'dispatch_steps', recordId: order.id, recordLabel: label,
          action: 'update', before: { status: 'resumed', resumed_at: click.at }, after: { status: 'hold', resumed_at: null },
        });
      }
    } catch (err: any) {
      alert(`Undo failed: ${err?.message || JSON.stringify(err)}`);
    } finally {
      setUndoBusy(false);
    }
  };

  // Detail drawer — opened by clicking an SO No. on any board card (order
  // or entry card); always shows the whole order. The clicked card is kept
  // because the drawer's Edit / Delete act on it (the order, or that entry).
  const [drawerCard, setDrawerCard] = useState<BoardCard | null>(null);
  const drawerOrderId = drawerCard ? (drawerCard.kind === 'order' ? drawerCard.order.id : drawerCard.entry.orderId) : null;
  const openDrawer = (card: BoardCard) => setDrawerCard(card);
  const closeDrawer = useCallback(() => setDrawerCard(null), []);

  const [toast, setToast] = useState<{ type: 'ok' | 'err'; msg: string } | null>(null);
  const showToast = (type: 'ok' | 'err', msg: string) => {
    setToast({ type, msg });
    setTimeout(() => setToast(null), 5000);
  };

  // ✎ Step edit (all users) — one dispatch_steps row: status, actual time
  // (done_at) and remark. Planned is always recalculated, never stored here.
  // The board, drawer and step counts all recalculate from stepRecords.
  const saveStepEdit = async (order: Order, rec: DispatchStepRecord, patch: StepEditPatch) => {
    const row = { status: patch.status, done_at: patch.doneAt, remark: patch.remark };
    const { data: updated, error } = await supabase.from('dispatch_steps').update(row).eq('id', rec.id).select('*');
    if (error) throw error;
    if (!updated || updated.length === 0) throw new Error("Nothing was saved — the step may have been removed, or you don't have permission.");
    setStepRecords(prev => prev.map(r => r.id === rec.id ? mapStepFromDB(updated[0]) : r));
    logActivity({
      module: 'dispatch_steps', recordId: order.id, recordLabel: stepLogLabel(order, rec.stepNo, 'Edited'),
      action: 'update',
      before: { status: rec.status, done_at: rec.doneAt ?? null, remark: rec.remark ?? null },
      after: row,
    });
    showToast('ok', `Step ${rec.stepNo} updated.`);
  };

  // DELETE (admins only — same canDeleteRecords as Enquiries / Quotes /
  // Orders). Order card → taken off the board (never deleted from Orders);
  // entry card → that one dispatch entry. Never touches orders' status.
  const [deleteCard, setDeleteCard] = useState<BoardCard | null>(null);
  const [deleting, setDeleting] = useState(false);
  const requestDelete = (card: BoardCard) => {
    if (!canDelete) return;
    if (card.kind === 'order') {
      const n = data.dispatchEntries.filter(e => e.orderId === card.order.id).length;
      if (n > 0) { showToast('err', `This order has ${n} dispatch entr${n === 1 ? 'y' : 'ies'}. Delete those entries first.`); return; }
    }
    setDeleteCard(card);
  };
  const confirmDelete = async () => {
    if (!deleteCard || !canDelete) return;
    setDeleting(true);
    try {
      if (deleteCard.kind === 'order') {
        const o = deleteCard.order;
        await removeOrderFromDispatch(o.id);
        setStepRecords(prev => prev.filter(r => r.orderId !== o.id));
        showToast('ok', `${o.soNumber || o.id} removed from the Dispatch board. It stays in Orders.`);
      } else {
        const e = deleteCard.entry;
        await deleteDispatchEntry(e.id);
        showToast('ok', `Dispatch entry ${e.invoiceNumber || e.id} deleted.`);
      }
      setDeleteCard(null);
      setDrawerCard(null);
    } catch (err) {
      setDeleteCard(null);
      showToast('err', `Delete failed: ${friendlyDeleteError(err)}`);
    } finally {
      setDeleting(false);
    }
  };

  const orderFor = (entry: DispatchEntry): Order | undefined => data.orders.find(o => o.id === entry.orderId);

  // Order Pending for Dispatch — read-only view of every order that was
  // sent here (sentToDispatchAt — the "Order Pending for Dispatch" button
  // in Orders), is still Order Confirmed (or legacy Order Pending for
  // Dispatch), and still has barrels left to dispatch (totalRemaining > 0).
  // A partial dispatch keeps the same order here until every line has gone
  // out; each dispatch shows under "Dispatched" as its own entry. Nothing
  // here changes an order's status.
  const pendingOrders = useMemo(
    () => data.orders.filter(o => !!o.sentToDispatchAt && (o.status === 'Order Confirmed' || o.status === 'Order Pending for Dispatch') && totalRemaining(o, data.dispatchEntries) > 0),
    [data.orders, data.dispatchEntries],
  );
  // Shown in the Fulfillment column only (this tab has no Delivery/Self
  // Pickup split) — order's own type first, then the customer's typical
  // pattern, else "Not Set".
  const orderFulfillment = (o: Order): SubType => {
    if (o.fulfillmentType === 'delivery' || o.fulfillmentType === 'self_pickup') return o.fulfillmentType;
    const cf = customerOfDoc(o, data.customers)?.fulfilmentType;
    if (cf === 'Delivery') return 'delivery';
    if (cf === 'Self Pickup') return 'self_pickup';
    return 'not_set';
  };

  // Assign SO numbers to every order shown anywhere on this page that
  // doesn't have one yet — pending orders plus every order linked to a
  // dispatch entry (covers orders dispatched before SO numbers existed).
  // The ref keeps it from ever running twice at once; once a run's saves
  // land in local state, missingSoKey changes and the effect re-checks for
  // anything that appeared in the meantime.
  const soRunning = useRef(false);
  const missingSoKey = useMemo(() => {
    const ids = new Set(pendingOrders.filter(o => !o.soNumber).map(o => o.id));
    for (const e of data.dispatchEntries) {
      // Entries imported from old "Delivered" orders never get an SO number.
      if (isImportedEntry(e)) continue;
      const o = data.orders.find(x => x.id === e.orderId);
      if (o && !o.soNumber) ids.add(o.id);
    }
    return [...ids].sort().join(',');
  }, [pendingOrders, data.dispatchEntries, data.orders]);
  useEffect(() => {
    if (!missingSoKey || soRunning.current) return;
    soRunning.current = true;
    ensureSoNumbers(missingSoKey.split(','))
      .catch(err => console.error('ensureSoNumbers failed:', err))
      .finally(() => { soRunning.current = false; });
  }, [missingSoKey]);

  const entries = data.dispatchEntries;
  // Each entry lives in exactly one of the two entry tabs:
  //   emailSentAt set (Email to Client succeeded) → Email Sent
  //   else                                        → Dispatched
  // (the old "Order → Dispatch" stage is retired — an entry without sentAt
  // still lands in Dispatched, so no entry is ever hidden). Both share the
  // same Delivery/Self Pickup sub-split.
  const emailSentEntries = entries.filter(e => e.emailSentAt);
  const sentEntries = entries.filter(e => !e.emailSentAt);
  const activeEntries = tab === 'emailSent' ? emailSentEntries : sentEntries;
  const deliveryCount = activeEntries.filter(e => e.fulfillmentType === 'delivery').length;
  const selfPickupCount = activeEntries.filter(e => e.fulfillmentType === 'self_pickup').length;

  // Keep the URL in step so a refresh stays on the same tab/pill/view.
  const syncUrl = (t: DispatchTab, type: DispatchFulfillmentType, v: 'table' | 'board' = view) =>
    setSearchParams({ ...(t === 'pending' ? {} : { tab: t, type }), ...(v === 'board' ? { view: 'board' } : {}) }, { replace: true });
  const switchTab = (t: DispatchTab) => {
    setTab(t);
    setExpandedRow(null);
    syncUrl(t, subType);
  };
  const switchSubType = (type: DispatchFulfillmentType) => {
    setSubType(type);
    syncUrl(tab, type);
  };
  const switchView = (v: 'table' | 'board') => {
    setView(v);
    syncUrl(tab, subType, v);
  };

  const qs = search.trim().toLowerCase();
  const orderMatches = (o: Order | undefined, fallbackId: string) => {
    if (!qs) return true;
    if (fallbackId.toLowerCase().includes(qs)) return true;
    if (!o) return false;
    return (o.soNumber || '').toLowerCase().includes(qs) ||
      normalizeSearchText(o.cust).includes(normalizeSearchText(qs)) ||
      (o.poNo || '').toLowerCase().includes(qs) ||
      o.items.some(i => (i.desc || '').toLowerCase().includes(qs));
  };

  const visiblePending = useMemo(
    () => pendingOrders
      .filter(o => orderMatches(o, o.id))
      .sort((a, b) => (b.created_at || b.poDate || '').localeCompare(a.created_at || a.poDate || '')),
    [pendingOrders, qs],
  );

  const visibleEntries = useMemo(
    () => activeEntries
      .filter(e => e.fulfillmentType === subType && (orderMatches(orderFor(e), e.orderId) ||
        (e.invoiceNumber || '').toLowerCase().includes(qs)))
      // Email Sent: newest email first; Dispatched: newest entry first.
      .sort((a, b) => tab === 'emailSent'
        ? (b.emailSentAt || '').localeCompare(a.emailSentAt || '')
        : (b.created_at || '').localeCompare(a.created_at || '')),
    [activeEntries, subType, qs, data.orders, tab],
  );

  const rowCount = tab === 'pending' ? visiblePending.length : visibleEntries.length;
  // Email Sent adds "Email Sent On" — Dispatched: 10 columns, Email Sent: 11.
  const isEmailSentTab = tab === 'emailSent';
  const entryColCount = isEmailSentTab ? 11 : 10;

  // ── Board view ──────────────────────────────────────────────────────────
  const boardCards = useMemo(
    () => view === 'board' ? buildBoard(data.orders, data.dispatchEntries, stepRecords, orderFulfillment, now) : [],
    [view, data.orders, data.dispatchEntries, data.customers, stepRecords, now],
  );
  const boardSearchMatch = (c: BoardCard) => {
    if (!qs) return true;
    const o = c.order;
    return (o?.soNumber || '').toLowerCase().includes(qs)
      || (c.kind === 'order' ? c.order.id : c.entry.orderId).toLowerCase().includes(qs)
      || (!!o && normalizeSearchText(o.cust).includes(normalizeSearchText(qs)))
      || (c.kind === 'entry' && (c.entry.invoiceNumber || '').toLowerCase().includes(qs));
  };
  // Type + search narrow everything; the All/Delayed/On hold pills then
  // filter what's left (their counts are shown before that last step).
  const boardBase = boardCards.filter(c => (boardType === 'both' || c.fulfillment === boardType) && boardSearchMatch(c));
  const boardDelayedCount = boardBase.filter(c => c.state === 'late').length;
  const boardHoldCount = boardBase.filter(c => c.state === 'hold').length;
  const boardVisible = boardFilter === 'delayed' ? boardBase.filter(c => c.state === 'late')
    : boardFilter === 'hold' ? boardBase.filter(c => c.state === 'hold')
    : boardBase;
  // Header count boxes — whole board, ignoring filters/search.
  const headerCounts = {
    inProgress: boardCards.filter(c => c.column !== DONE_COLUMN).length,
    delayed: boardCards.filter(c => c.state === 'late').length,
    onHold: boardCards.filter(c => c.state === 'hold').length,
    emailSent: boardCards.filter(c => c.column === DONE_COLUMN).length,
  };

  return (
    <div className="flex flex-col h-full animate-in fade-in duration-300">
      <div className="pt-5 px-6">
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="font-mono text-[9px] font-bold tracking-[3px] uppercase text-red-mrt mb-1">Module 04</div>
            <h1 className="font-serif text-2xl text-blk tracking-tight leading-tight">
              Dispatch <em className="italic text-red-mrt">Control</em>
            </h1>
            <p className="text-xs text-g500 mt-1 font-light">Every confirmed order, stage by stage — split by how it leaves the warehouse.</p>
          </div>
          {view === 'board' && (
            <div className="flex items-stretch gap-2 shrink-0">
              {([
                ['In progress', headerCounts.inProgress, 'bg-white text-blk'],
                ['Delayed', headerCounts.delayed, 'bg-[#FFEBEE] text-[#9A0000]'],
                ['On hold', headerCounts.onHold, 'bg-white text-blk'],
                ['Email sent', headerCounts.emailSent, 'bg-[#E8F5E9] text-[#0B5C2A]'],
              ] as const).map(([label, count, cls]) => (
                <div key={label} className={`border border-g200 rounded-[6px] px-3 py-1.5 min-w-[92px] ${cls}`}>
                  <div className="font-mono text-[8.5px] font-bold tracking-[1.5px] uppercase opacity-80">{label}</div>
                  <div className="text-[22px] font-bold leading-tight">{count}</div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2 px-6 py-2.5 mt-4 bg-white border-b border-g200 flex-wrap">
        <div className="flex gap-[1px] bg-g100 border border-g200 rounded p-[2px]">
          <div onClick={() => switchView('table')} className={`flex items-center gap-1.5 ${pillCls(view === 'table')}`}>
            <List size={12} /> Table
          </div>
          <div onClick={() => switchView('board')} className={`flex items-center gap-1.5 ${pillCls(view === 'board')}`}>
            <Columns3 size={12} /> Board
          </div>
        </div>
        <div className="w-px h-[18px] bg-g200 shrink-0 mx-1"></div>

        {view === 'board' ? (
          <>
            <div className="flex gap-[1px] bg-g100 border border-g200 rounded p-[2px]">
              <div onClick={() => setBoardFilter('all')} className={pillCls(boardFilter === 'all')}>All ({boardBase.length})</div>
              <div onClick={() => setBoardFilter('delayed')} className={pillCls(boardFilter === 'delayed')}>Delayed ({boardDelayedCount})</div>
              <div onClick={() => setBoardFilter('hold')} className={pillCls(boardFilter === 'hold')}>On hold ({boardHoldCount})</div>
            </div>
            <div className="w-px h-[18px] bg-g200 shrink-0 mx-1"></div>
            <div className="flex gap-[1px] bg-g100 border border-g200 rounded p-[2px]">
              <div onClick={() => setBoardType('both')} className={pillCls(boardType === 'both')}>Both</div>
              <div onClick={() => setBoardType('delivery')} className={`flex items-center gap-1.5 ${pillCls(boardType === 'delivery')}`}>
                <span className="w-[7px] h-[7px] rounded-full bg-[#2563EB] shrink-0" /> Delivery
              </div>
              <div onClick={() => setBoardType('self_pickup')} className={`flex items-center gap-1.5 ${pillCls(boardType === 'self_pickup')}`}>
                <span className="w-[7px] h-[7px] rounded-full bg-[#7C3AED] shrink-0" /> Self Pickup
              </div>
            </div>
            <div className="w-px h-[18px] bg-g200 shrink-0 mx-1"></div>
            <div className="flex items-center gap-1.5 bg-white border border-g200 rounded px-2 h-7 min-w-[220px] transition-colors focus-within:border-red-mrt focus-within:ring-2 focus-within:ring-red-lt">
              <Search size={11} className="text-g400 shrink-0" />
              <input
                type="text"
                placeholder="SO No, Order Ref, company, invoice…"
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="bg-transparent border-none outline-none font-sans text-xs text-blk w-full placeholder:text-g400"
              />
            </div>
            <div className="ml-auto flex items-center gap-3 text-[11px] text-g600 whitespace-nowrap">
              <span className="inline-flex items-center gap-1"><span className="w-[7px] h-[7px] rounded-full bg-[#107E3E]" />On time</span>
              <span className="inline-flex items-center gap-1"><span className="w-[7px] h-[7px] rounded-full bg-[#E9730C]" />Due within 1h</span>
              <span className="inline-flex items-center gap-1"><span className="w-[7px] h-[7px] rounded-full bg-[#BB0000]" />Delayed</span>
              <span className="inline-flex items-center gap-1"><AutoTag /> Moves by itself</span>
            </div>
          </>
        ) : (<>
        <div className="flex gap-[1px] bg-g100 border border-g200 rounded p-[2px]">
          <div onClick={() => switchTab('pending')} className={pillCls(tab === 'pending')}>
            Order Pending for Dispatch ({pendingOrders.length})
          </div>
          <div onClick={() => switchTab('dispatched')} className={pillCls(tab === 'dispatched')}>
            Dispatched ({sentEntries.length})
          </div>
          <div onClick={() => switchTab('emailSent')} className={pillCls(tab === 'emailSent')}>
            Email Sent ({emailSentEntries.length})
          </div>
        </div>

        {tab !== 'pending' && (
          <>
            <div className="w-px h-[18px] bg-g200 shrink-0 mx-1"></div>
            <div className="flex gap-[1px] bg-g100 border border-g200 rounded p-[2px]">
              <div onClick={() => switchSubType('delivery')} className={`flex items-center gap-1.5 ${pillCls(subType === 'delivery')}`}>
                <span className="w-[7px] h-[7px] rounded-full bg-sN shrink-0" /> Delivery ({deliveryCount})
              </div>
              <div onClick={() => switchSubType('self_pickup')} className={`flex items-center gap-1.5 ${pillCls(subType === 'self_pickup')}`}>
                <span className="w-[7px] h-[7px] rounded-full bg-[#7C3AED] shrink-0" /> Self Pickup ({selfPickupCount})
              </div>
            </div>
          </>
        )}

        <div className="w-px h-[18px] bg-g200 shrink-0 mx-1"></div>
        <div className="flex items-center gap-1.5 bg-white border border-g200 rounded px-2 h-7 min-w-[200px] transition-colors focus-within:border-red-mrt focus-within:ring-2 focus-within:ring-red-lt">
          <Search size={11} className="text-g400 shrink-0" />
          <input
            type="text"
            placeholder="SO No, Order Ref, company, PO No, item..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="bg-transparent border-none outline-none font-sans text-xs text-blk w-full placeholder:text-g400"
          />
        </div>

        <div className="ml-auto font-mono text-[10px] text-g500">
          {tab === 'pending' ? `${rowCount} order(s)` : `${rowCount} entr${rowCount === 1 ? 'y' : 'ies'}`}
        </div>
        </>)}
      </div>

      {view === 'board' ? (
        <DispatchBoard cards={boardVisible} now={now} onOpen={openDrawer} renderActions={renderBoardActions} onDelete={canDelete ? requestDelete : undefined} />
      ) : (
      <div className="px-6 pb-7 pt-[14px] flex-1 overflow-y-auto">
        <div className="bg-white border border-g200 overflow-x-auto m-0">
          {tab === 'pending' ? (
            <table className="w-full border-collapse text-[12.5px]">
              <thead className="bg-g100">
                <tr>
                  <th className={thCls}>SO No.</th>
                  <th className={thCls}>Order Ref</th>
                  <th className={thCls}>Customer - Unit</th>
                  <th className={thCls}>PO Number</th>
                  <th className={thCls}>PO Date</th>
                  <th className={thCls}>Schedule Date</th>
                  <th className={thCls}>Items</th>
                  <th className={thRightCls}>Order Value</th>
                  <th className={thCls}>Fulfillment</th>
                  <th className={thCls}>Punched At</th>
                  <th className={thCls}>Status</th>
                  <th className={thCls}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {visiblePending.length === 0 ? (
                  <tr><td colSpan={12} className="text-center p-8 text-g400 text-[13px]">
                    {qs ? 'No matching orders' : 'No confirmed orders pending for dispatch'}
                  </td></tr>
                ) : (
                  visiblePending.map(o => {
                    const subTotal = o.items.reduce((s, i) => s + i.total, 0);
                    const itemGst = o.items.reduce((s, i) => s + (i.total * i.gst / 100), 0);
                    const grandTotal = resolveAdjustments(o.adjustments, subTotal, itemGst, maxItemGstRate(o.items)).grand;
                    const isExpanded = expandedRow === o.id;
                    const sl = siteLabel(customerOfDoc(o, data.customers), o.siteId || data.enquiries.find(e => e.id === o.enqRef)?.siteId);
                    return (
                      <React.Fragment key={o.id}>
                        <tr
                          className={`group transition-colors cursor-pointer border-b border-g100 last:border-b-0 hover:bg-sW/5 ${isExpanded ? 'bg-sW/5' : ''}`}
                          onClick={() => setExpandedRow(isExpanded ? null : o.id)}
                        >
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap"><SoCell soNumber={o.soNumber} hasOrder /></td>
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap"><span className="font-mono text-[10px] font-bold text-sQ">{o.id}</span></td>
                          <td className="px-[13px] py-[10px] align-top">
                            <div className="font-semibold">{o.cust}{sl ? <span className="font-normal text-g500"> — {sl}</span> : null}</div>
                          </td>
                          <td className="px-[13px] py-[10px] align-top font-mono text-[11px] font-bold text-g700">{o.poNo || '—'}</td>
                          <td className="px-[13px] py-[10px] align-top text-[11.5px] text-g600 whitespace-nowrap">
                            {o.poDate ? fmtIST(new Date(o.poDate), 'dd-MMM-yyyy') : '--'}
                          </td>
                          <td className="px-[13px] py-[10px] align-top text-[11.5px] text-g600 whitespace-nowrap">
                            {o.scheduleDate ? fmtIST(new Date(o.scheduleDate), 'dd-MMM-yyyy') : '--'}
                          </td>
                          <td className="px-[13px] py-[10px] align-top">
                            <span className="font-mono text-[10px] font-bold bg-g100 text-g600 px-[7px] py-[2px] rounded-full inline-flex items-center">
                              {o.items.length} item(s)
                            </span>
                          </td>
                          <td className="px-[13px] py-[10px] align-top text-right font-mono text-[12px] font-bold">{formatINR(Math.round(grandTotal))}</td>
                          <td className="px-[13px] py-[10px] align-top">{fulfillmentLabel(orderFulfillment(o))}</td>
                          <td className="px-[13px] py-[10px] align-top text-[11.5px] whitespace-nowrap">
                            {o.created_at ? (() => {
                              const cls = punchedAtClass(o.created_at);
                              return <span className={cls.text} title={cls.title}>{fmtIST(new Date(o.created_at), 'dd-MMM-yyyy')}</span>;
                            })() : <span className="text-g600">--</span>}
                          </td>
                          <td className="px-[13px] py-[10px] align-top"><Badge status={o.status} /></td>
                          <td className="px-[13px] py-[10px] align-top" onClick={ev => ev.stopPropagation()}>
                            <Button size="sm" variant="success" className="active:scale-95 transition-transform" onClick={() => navigate(`/dispatch/new?orderRef=${o.id}&toSent=1`)}>Create Dispatch</Button>
                          </td>
                        </tr>
                        {isExpanded && (
                          <tr className="bg-sW/[0.02] border-b-2 border-sW">
                            <td colSpan={12} className="p-0">
                              <LineItemsPanel title={`Order Line Items -- ${o.soNumber ? `${o.soNumber} / ` : ''}${o.id}`} items={o.items} grand={grandTotal} />
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    );
                  })
                )}
              </tbody>
            </table>
          ) : (
            // Fixed layout + fixed column widths so the Delivery and Self
            // Pickup pills render identically instead of auto-sizing to
            // whatever rows happen to be showing.
            <table className="w-full table-fixed border-collapse text-[12.5px]">
              <colgroup>
                <col style={{ width: 110 }} />{/* SO No. */}
                <col style={{ width: 110 }} />{/* Order Ref */}
                <col style={{ width: 200 }} />{/* Customer */}
                <col style={{ width: 120 }} />{/* PO No. */}
                <col style={{ width: 90 }} />{/* Items */}
                <col style={{ width: 120 }} />{/* Value */}
                <col style={{ width: 150 }} />{/* Transporter */}
                <col style={{ width: 110 }} />{/* Invoice No. */}
                <col style={{ width: 115 }} />{/* Dispatched On */}
                {isEmailSentTab && <col style={{ width: 165 }} />}{/* Email Sent On */}
                <col style={{ width: 260 }} />{/* Actions — wide enough for Edit + Delete side by side */}
              </colgroup>
              <thead className="bg-g100">
                <tr>
                  <th className={thCls}>SO No.</th>
                  <th className={thCls}>Order Ref</th>
                  <th className={thCls}>Customer</th>
                  <th className={thCls}>PO No.</th>
                  <th className={thCls}>Items</th>
                  <th className={thRightCls}>Value</th>
                  <th className={thCls}>Transporter</th>
                  {/* Promised/Estimated Delivery dates stay saved and visible
                      in the Edit form — this list shows Invoice No. instead. */}
                  <th className={thCls}>Invoice No.</th>
                  <th className={thCls}>Dispatched On</th>
                  {isEmailSentTab && <th className={thCls}>Email Sent On</th>}
                  <th className={thCls}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {visibleEntries.length === 0 ? (
                  <tr><td colSpan={entryColCount} className="text-center p-8 text-g400 text-[13px]">{qs ? 'No matching entries' : `No ${subType === 'self_pickup' ? 'Self Pickup' : 'Delivery'} entries ${tab === 'emailSent' ? 'emailed yet' : 'dispatched yet'}`}</td></tr>
                ) : (
                  visibleEntries.map(entry => {
                    const order = orderFor(entry);
                    const isExpanded = expandedRow === entry.id;
                    const lineItems = (entry.items && entry.items.length > 0) ? entry.items : (order?.items || []);
                    return (
                      <React.Fragment key={entry.id}>
                        <tr
                          className={`group transition-colors cursor-pointer border-b border-g100 last:border-b-0 hover:bg-sW/5 ${isExpanded ? 'bg-sW/5' : ''}`}
                          onClick={() => setExpandedRow(isExpanded ? null : entry.id)}
                        >
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap"><SoCell soNumber={order?.soNumber} hasOrder={!!order && !isImportedEntry(entry)} /></td>
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap"><span className="font-mono text-[10px] font-bold text-sQ">{entry.orderId}</span></td>
                          <td className="px-[13px] py-[10px] align-top break-words">
                            <div className="font-semibold">{order?.cust || '—'}</div>
                          </td>
                          <td className="px-[13px] py-[10px] align-top font-mono text-[10.5px] break-words">{order?.poNo || '—'}</td>
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap">{entry.items?.length ?? 0} item(s)</td>
                          <td className="px-[13px] py-[10px] align-top text-right font-mono text-[12px] font-bold whitespace-nowrap">{formatINR(Math.round(entry.value || 0))}</td>
                          <td className="px-[13px] py-[10px] align-top break-words">{entry.transporter || '—'}</td>
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap">
                            {entry.invoiceNumber
                              ? <span className="block truncate font-mono text-[10.5px] font-semibold" title={entry.invoiceNumber}>{entry.invoiceNumber}</span>
                              : <span className="text-g400">—</span>}
                          </td>
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap">{entry.created_at ? fmtIST(new Date(entry.created_at), 'dd-MMM-yyyy') : '—'}</td>
                          {isEmailSentTab && (
                            <td className="px-[13px] py-[10px] align-top whitespace-nowrap">{entry.emailSentAt ? fmtIST(new Date(entry.emailSentAt), 'dd-MMM-yyyy hh:mm a') : '—'}</td>
                          )}
                          <td className="px-[13px] py-[10px] align-top whitespace-nowrap" onClick={ev => ev.stopPropagation()}>
                            <div className="flex flex-col gap-[3px]">
                              <div className="flex items-center gap-1.5 flex-nowrap">
                                <Button size="sm" variant="secondary" onClick={() => navigate(`/dispatch/new?entryId=${entry.id}`)}>Edit</Button>
                                {canDelete && (
                                  <Button size="sm" variant="ghost" className="text-red-500 hover:text-red-700 hover:bg-red-50" onClick={async () => {
                                    if (!confirm(`Are you sure you want to delete the dispatch entry for ${entry.orderId}? This action cannot be undone.`)) return;
                                    try {
                                      await deleteDispatchEntry(entry.id);
                                    } catch (err: any) {
                                      alert(`Delete failed: ${err?.message || JSON.stringify(err)}`);
                                    }
                                  }}>Delete</Button>
                                )}
                              </div>
                              {/* 2026-09-21: shows just the name of whoever made the most
                                  recent change — updatedBy if the entry's been edited since
                                  it was created, else createdBy — resolved through the team
                                  roster to a display name (falls back to the raw email if
                                  no roster match), single line, no "Created:"/"Updated:"
                                  label, positioned under the action buttons. */}
                              {(entry.updatedBy || entry.createdBy) && (
                                <span className="text-[10px] font-mono text-g400 whitespace-nowrap">{doerLabel(entry.updatedBy || entry.createdBy, data.roster)}</span>
                              )}
                            </div>
                          </td>
                        </tr>

                        {isExpanded && (
                          <tr className="bg-sW/[0.02] border-b-2 border-sW">
                            <td colSpan={entryColCount} className="p-0">
                              <LineItemsPanel title={`Dispatch Line Items -- ${entry.orderId}`} items={lineItems} grand={entry.value || 0} />
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    );
                  })
                )}
              </tbody>
            </table>
          )}
        </div>
      </div>
      )}

      {view === 'board' && drawerOrderId && (() => {
        const o = data.orders.find(x => x.id === drawerOrderId);
        if (!o) return null;
        // Unfiltered board, so the drawer still finds the order card when
        // the current filter/search hides it.
        const orderCard = boardCards.find((c): c is BoardOrderCard => c.kind === 'order' && c.order.id === o.id);
        return (
          <DispatchDrawer
            order={o}
            entries={data.dispatchEntries.filter(e => e.orderId === o.id)}
            records={stepRecords.filter(r => r.orderId === o.id)}
            fulfillment={orderCard?.fulfillment ?? orderFulfillment(o)}
            orderCard={orderCard}
            now={now}
            roster={data.roster}
            canAct={canActOnBoard}
            busy={!!orderCard && busyCardKey === orderCard.key}
            onAction={handleStepAction}
            onResume={resumeHold}
            canUndo={canUndoOnBoard}
            undoBusy={undoBusy}
            onUndo={() => undoLastStep(o)}
            openedFrom={boardCards.find(c => c.key === drawerCard?.key) ?? drawerCard!}
            canDelete={canDelete}
            onSaveStep={(rec, patch) => saveStepEdit(o, rec, patch)}
            onDelete={requestDelete}
            onClose={closeDrawer}
          />
        );
      })()}

      {deleteCard && (
        deleteCard.kind === 'order' ? (
          <ConfirmDialog
            title={`Remove ${deleteCard.order.soNumber || deleteCard.order.id} – ${deleteCard.order.cust} from the Dispatch board?`}
            confirmLabel="Remove"
            busy={deleting}
            onConfirm={confirmDelete}
            onCancel={() => setDeleteCard(null)}
          >
            The order stays in Orders and can be sent to Dispatch again.
          </ConfirmDialog>
        ) : (
          <ConfirmDialog
            title={`Delete dispatch entry ${deleteCard.entry.invoiceNumber || deleteCard.entry.id} for ${deleteCard.order?.cust || deleteCard.entry.orderId}?`}
            confirmLabel="Delete"
            busy={deleting}
            onConfirm={confirmDelete}
            onCancel={() => setDeleteCard(null)}
          >
            This cannot be undone. The quantity will go back to Order Pending for Dispatch.
          </ConfirmDialog>
        )
      )}

      {toast && (
        <div className={`fixed bottom-5 right-5 z-[60] max-w-[440px] flex items-center gap-2 px-4 py-2.5 rounded-[4px] shadow-lg text-[12.5px] font-medium text-white animate-in slide-in-from-bottom-2 ${toast.type === 'ok' ? 'bg-sW' : 'bg-red-mrt'}`}>
          {toast.type === 'ok' && <CheckCircle2 size={14} className="shrink-0" />}
          {toast.msg}
        </div>
      )}
    </div>
  );
}
